[server]
enableStaticServing = false
headless = true
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[client]
toolbarMode = "minimal"
caching = true

[runner]
fastReruns = true
